### ISSUE TITLE
Can you tag version?

### ISSUE THREAD

**Issue by vslinko** [seiffert/require-jsx#4]
I want use that library from cdnjs.com but they requires tagget commit.

https://github.com/cdnjs/cdnjs/pull/1729#issuecomment-22991777

**Comment by sjamaan** [comment]
Same for bower.io

Works now by directly linking to a commit, like

``` json
{
  "dependencies": {
    "requirejsx": "git://github.com/seiffert/require-jsx#c20d66daaaa163b6a5f3147fb47c698936199fc5"
  }
}
```

But that's kind of ugly. Semver dependencies are much nicer.

**Comment by graingert** [comment]
Yeah this is basically a requirement for including in production Bower-using projects.

**Comment by graingert** [comment]
Why did you close this @vslinko ?

**Comment by vslinko** [comment]
Sorry, I'm closing all irrelevant issues. This issue is irrelevant because:
- last commit was in 2014, so I guess this project is abandoned
- this project doesn't support edge version of React
